# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import config


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 600)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("color: rgb(255, 170, 127);")
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        self.widget.setMinimumSize(QtCore.QSize(1024, 600))
        self.widget.setStyleSheet("background-color: #17AEAA;")
        self.widget.setObjectName("widget")
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setGeometry(QtCore.QRect(40, 30, 931, 531))
        self.frame_2.setStyleSheet("border: 1px  ;\n"
"border-radius: 40px; \n"
"background-color: #FFF6ED;\n"
"align-items: center;")
        self.frame_2.setObjectName("frame_2")
        self.widget_3 = QtWidgets.QWidget(self.frame_2)
        self.widget_3.setGeometry(QtCore.QRect(90, 310, 91, 51))
        self.widget_3.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"background-color: #17AEAA;\n"
"border-radius: 14px")
        self.widget_3.setObjectName("widget_3")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.widget_3)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 10, 91, 31))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.widget_4 = QtWidgets.QWidget(self.frame_2)
        self.widget_4.setGeometry(QtCore.QRect(200, 310, 91, 51))
        self.widget_4.setStyleSheet("background-color: #17AEAA;\n"
"border-radius: 14px;")
        self.widget_4.setObjectName("widget_4")
        # Left logo (32x32)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(20, 16, 32, 32))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(config.LOGO_PATH))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")

        # Right-aligned bar with three icons
        self.rightIcons = QtWidgets.QWidget(self.frame_2)
        self.rightIcons.setGeometry(QtCore.QRect(760, 16, 121, 32))
        self.rightIcons.setObjectName("rightIcons")
        self.rightIconsLayout = QtWidgets.QHBoxLayout(self.rightIcons)
        self.rightIconsLayout.setContentsMargins(0, 0, 0, 0)
        self.rightIconsLayout.setSpacing(8)
        self.rightIconsLayout.setObjectName("rightIconsLayout")
        # Only the three navigation icons on the right
        self.user_right = QtWidgets.QLabel(self.rightIcons)
        self.user_right.setText("")
        self.user_right.setPixmap(QtGui.QPixmap(config.USER_ICON_PATH))
        self.user_right.setScaledContents(True)
        self.user_right.setMinimumSize(QtCore.QSize(32, 32))
        self.user_right.setMaximumSize(QtCore.QSize(32, 32))
        self.rightIconsLayout.addWidget(self.user_right)
        self.report_right = QtWidgets.QLabel(self.rightIcons)
        self.report_right.setText("")
        self.report_right.setPixmap(QtGui.QPixmap(config.REPORT_ICON_PATH))
        self.report_right.setScaledContents(True)
        self.report_right.setMinimumSize(QtCore.QSize(32, 32))
        self.report_right.setMaximumSize(QtCore.QSize(32, 32))
        self.rightIconsLayout.addWidget(self.report_right)
        self.settings_right = QtWidgets.QLabel(self.rightIcons)
        self.settings_right.setText("")
        self.settings_right.setPixmap(QtGui.QPixmap(config.SETTINGS_ICON_PATH))
        self.settings_right.setScaledContents(True)
        self.settings_right.setMinimumSize(QtCore.QSize(32, 32))
        self.settings_right.setMaximumSize(QtCore.QSize(32, 32))
        self.rightIconsLayout.addWidget(self.settings_right)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.frame_2)
        self.dateTimeEdit.setGeometry(QtCore.QRect(720, 490, 171, 22))
        self.dateTimeEdit.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 13pt;")
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(80, 200, 401, 61))
        self.label_5.setStyleSheet("font-size:56px;\n"
"color:black;")
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">HOME</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "Welcome Admin"))
